# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Location
version:      0.6
version_from: lib/HTML/Location.pm
installdirs:  site
requires:
    Clone:                         0.13
    File::Spec:                    0.83
    List::Util:                    1.11
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
