name: HTML-Location
version: 1.01
abstract: Working with disk to URI file mappings (deprecated: see URI::ToDisk)
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  Clone: 0.13
  List::Util: 1.11
  URI: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
