---
abstract: 'Working with disk to URI file mappings (deprecated: see URI::ToDisk)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Location
name: HTML-Location
no_index:
  directory:
    - inc
    - t
requires:
  Clone: 0.31
  File::Spec: 0.80
  List::Util: 1.11
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
