--- #YAML:1.0
name:                HTML-Location
version:             1.02
abstract:            Working with disk to URI file mappings (deprecated: see URI::ToDisk)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Clone:                         0.31
    File::Spec:                    0.80
    List::Util:                    1.11
    Test::More:                    0.47
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam Kennedy <adamk@cpan.org>
